I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/route_conflicts.rpy", line 173, in script
    with dialogue
  File "game/route_conflicts.rpy", line 173, in <module>
    with dialogue
NameError: name 'dialogue' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/route_conflicts.rpy", line 173, in script
    with dialogue
  File "C:\renpy\renpy-8.3.7-sdk\renpy\ast.py", line 1367, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\renpy\renpy-8.3.7-sdk\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\renpy\renpy-8.3.7-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/route_conflicts.rpy", line 173, in <module>
    with dialogue
NameError: name 'dialogue' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.7.25031702
Shadow Hunting 1.0
Fri May 30 23:27:01 2025
